CREATE TABLE IF NOT EXISTS `user` (
    `id` VARCHAR(36) PRIMARY KEY,
    `username` VARCHAR(100) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `display_name` VARCHAR(100) NOT NULL,
    `role` VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `equipment` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(200) NOT NULL,
    `code` VARCHAR(50) NOT NULL UNIQUE,
    `category` VARCHAR(30) NOT NULL COMMENT 'INSTRUMENT/CONSUMABLE/SOFTWARE/OTHER',
    `location` VARCHAR(200) DEFAULT '',
    `total_quantity` INT NOT NULL DEFAULT 0,
    `available_quantity` INT NOT NULL DEFAULT 0,
    `status` VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE' COMMENT 'AVAILABLE/MAINTENANCE/RETIRED',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `borrow_record` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(36) NOT NULL,
    `equipment_id` BIGINT NOT NULL,
    `quantity` INT NOT NULL DEFAULT 1,
    `start_time` DATETIME DEFAULT NULL,
    `end_time` DATETIME DEFAULT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED/RETURNED',
    `reject_reason` VARCHAR(500) DEFAULT '',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `user`(`id`),
    FOREIGN KEY (`equipment_id`) REFERENCES `equipment`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Preload equipment data (code generated as UUID in service; static UUIDs for demo)
INSERT INTO `equipment` (`name`, `code`, `category`, `location`, `total_quantity`, `available_quantity`, `status`) VALUES
('电子显微镜', UUID(), 'INSTRUMENT', 'A栋101室', 3, 3, 'AVAILABLE'),
('离心机', UUID(), 'INSTRUMENT', 'A栋102室', 5, 5, 'AVAILABLE'),
('移液枪套装', UUID(), 'CONSUMABLE', 'B栋201室', 20, 20, 'AVAILABLE'),
('实验手套（箱）', UUID(), 'CONSUMABLE', 'B栋202室', 50, 50, 'AVAILABLE'),
('Matlab 授权', UUID(), 'SOFTWARE', '网络授权', 10, 10, 'AVAILABLE'),
('Office 365 授权', UUID(), 'SOFTWARE', '网络授权', 30, 30, 'AVAILABLE');

-- Sample equipment (≈100 items for demo display)
INSERT INTO `equipment` (`name`, `code`, `category`, `location`, `total_quantity`, `available_quantity`, `status`) VALUES
('荧光显微镜', UUID(), 'INSTRUMENT', 'A栋103室', 2, 2, 'AVAILABLE'),
('扫描电子显微镜', UUID(), 'INSTRUMENT', 'A栋101室', 1, 1, 'AVAILABLE'),
('透射电子显微镜', UUID(), 'INSTRUMENT', 'A栋101室', 1, 0, 'MAINTENANCE'),
('共聚焦显微镜', UUID(), 'INSTRUMENT', 'A栋103室', 2, 2, 'AVAILABLE'),
('体式显微镜', UUID(), 'INSTRUMENT', 'A栋104室', 4, 4, 'AVAILABLE'),
('倒置显微镜', UUID(), 'INSTRUMENT', 'A栋104室', 3, 2, 'AVAILABLE'),
('高速离心机', UUID(), 'INSTRUMENT', 'A栋102室', 3, 3, 'AVAILABLE'),
('超高速离心机', UUID(), 'INSTRUMENT', 'A栋102室', 1, 1, 'AVAILABLE'),
('冷冻离心机', UUID(), 'INSTRUMENT', 'A栋105室', 2, 1, 'AVAILABLE'),
('微量离心机', UUID(), 'INSTRUMENT', 'A栋105室', 6, 6, 'AVAILABLE'),
('PCR 扩增仪', UUID(), 'INSTRUMENT', 'A栋201室', 8, 8, 'AVAILABLE'),
('实时荧光定量 PCR', UUID(), 'INSTRUMENT', 'A栋201室', 4, 4, 'AVAILABLE'),
('凝胶电泳仪', UUID(), 'INSTRUMENT', 'A栋202室', 10, 9, 'AVAILABLE'),
('蛋白电泳仪', UUID(), 'INSTRUMENT', 'A栋202室', 8, 8, 'AVAILABLE'),
('转膜仪', UUID(), 'INSTRUMENT', 'A栋202室', 5, 5, 'AVAILABLE'),
('紫外分光光度计', UUID(), 'INSTRUMENT', 'A栋203室', 3, 3, 'AVAILABLE'),
('荧光分光光度计', UUID(), 'INSTRUMENT', 'A栋203室', 2, 2, 'AVAILABLE'),
('原子吸收光谱仪', UUID(), 'INSTRUMENT', 'A栋204室', 1, 1, 'AVAILABLE'),
('高效液相色谱仪', UUID(), 'INSTRUMENT', 'A栋205室', 3, 2, 'AVAILABLE'),
('气相色谱仪', UUID(), 'INSTRUMENT', 'A栋205室', 2, 2, 'AVAILABLE'),
('质谱仪', UUID(), 'INSTRUMENT', 'A栋206室', 1, 1, 'AVAILABLE'),
('核磁共振波谱仪', UUID(), 'INSTRUMENT', 'A栋206室', 1, 0, 'MAINTENANCE'),
('流式细胞仪', UUID(), 'INSTRUMENT', 'A栋301室', 2, 2, 'AVAILABLE'),
('酶标仪', UUID(), 'INSTRUMENT', 'A栋301室', 4, 4, 'AVAILABLE'),
('CO2 培养箱', UUID(), 'INSTRUMENT', 'B栋101室', 6, 6, 'AVAILABLE'),
('生物安全柜', UUID(), 'INSTRUMENT', 'B栋102室', 5, 4, 'AVAILABLE'),
('超净工作台', UUID(), 'INSTRUMENT', 'B栋103室', 8, 8, 'AVAILABLE'),
('恒温培养箱', UUID(), 'INSTRUMENT', 'B栋104室', 10, 10, 'AVAILABLE'),
('摇床', UUID(), 'INSTRUMENT', 'B栋104室', 6, 6, 'AVAILABLE'),
('发酵罐', UUID(), 'INSTRUMENT', 'B栋105室', 2, 2, 'AVAILABLE'),
('纯水机', UUID(), 'INSTRUMENT', 'B栋106室', 3, 3, 'AVAILABLE'),
('高压灭菌锅', UUID(), 'INSTRUMENT', 'B栋106室', 4, 4, 'AVAILABLE'),
('超声波清洗机', UUID(), 'INSTRUMENT', 'B栋107室', 5, 5, 'AVAILABLE'),
('冷冻干燥机', UUID(), 'INSTRUMENT', 'B栋108室', 2, 2, 'AVAILABLE'),
('旋转蒸发仪', UUID(), 'INSTRUMENT', 'B栋109室', 3, 3, 'AVAILABLE'),
('分析天平', UUID(), 'INSTRUMENT', 'C栋101室', 10, 10, 'AVAILABLE'),
('精密天平', UUID(), 'INSTRUMENT', 'C栋101室', 8, 7, 'AVAILABLE'),
('pH 计', UUID(), 'INSTRUMENT', 'C栋102室', 15, 15, 'AVAILABLE'),
('电导率仪', UUID(), 'INSTRUMENT', 'C栋102室', 5, 5, 'AVAILABLE'),
('搅拌器', UUID(), 'INSTRUMENT', 'C栋103室', 20, 20, 'AVAILABLE'),
('水浴锅', UUID(), 'INSTRUMENT', 'C栋103室', 12, 12, 'AVAILABLE'),
('烘箱', UUID(), 'INSTRUMENT', 'C栋104室', 8, 8, 'AVAILABLE'),
('马弗炉', UUID(), 'INSTRUMENT', 'C栋104室', 2, 2, 'AVAILABLE'),
('万能试验机', UUID(), 'INSTRUMENT', 'C栋201室', 1, 1, 'AVAILABLE'),
('硬度计', UUID(), 'INSTRUMENT', 'C栋201室', 2, 2, 'AVAILABLE'),
('3D 打印机', UUID(), 'INSTRUMENT', 'C栋202室', 3, 2, 'AVAILABLE'),
('激光切割机', UUID(), 'INSTRUMENT', 'C栋202室', 1, 1, 'AVAILABLE'),
('CNC 雕刻机', UUID(), 'INSTRUMENT', 'C栋203室', 1, 1, 'AVAILABLE'),
('金相显微镜', UUID(), 'INSTRUMENT', 'C栋203室', 3, 3, 'AVAILABLE'),
('X 射线衍射仪', UUID(), 'INSTRUMENT', 'C栋204室', 1, 1, 'AVAILABLE'),
('差示扫描量热仪', UUID(), 'INSTRUMENT', 'C栋204室', 1, 1, 'AVAILABLE'),
('热重分析仪', UUID(), 'INSTRUMENT', 'C栋204室', 1, 1, 'AVAILABLE'),
('移液器 (10 μL)', UUID(), 'CONSUMABLE', 'B栋201室', 50, 50, 'AVAILABLE'),
('移液器 (100 μL)', UUID(), 'CONSUMABLE', 'B栋201室', 50, 48, 'AVAILABLE'),
('移液器 (1000 μL)', UUID(), 'CONSUMABLE', 'B栋201室', 40, 40, 'AVAILABLE'),
('多道移液器 (8道)', UUID(), 'CONSUMABLE', 'B栋201室', 10, 10, 'AVAILABLE'),
('多道移液器 (12道)', UUID(), 'CONSUMABLE', 'B栋201室', 10, 10, 'AVAILABLE'),
('无菌培养皿 (包)', UUID(), 'CONSUMABLE', 'B栋301室', 100, 100, 'AVAILABLE'),
('细胞培养瓶', UUID(), 'CONSUMABLE', 'B栋301室', 80, 80, 'AVAILABLE'),
('离心管 (1.5 mL)', UUID(), 'CONSUMABLE', 'B栋302室', 200, 200, 'AVAILABLE'),
('离心管 (15 mL)', UUID(), 'CONSUMABLE', 'B栋302室', 150, 150, 'AVAILABLE'),
('离心管 (50 mL)', UUID(), 'CONSUMABLE', 'B栋302室', 120, 120, 'AVAILABLE'),
('PCR 管 (0.2 mL)', UUID(), 'CONSUMABLE', 'B栋303室', 300, 300, 'AVAILABLE'),
('PCR 八联管', UUID(), 'CONSUMABLE', 'B栋303室', 100, 100, 'AVAILABLE'),
('一次性吸头 (10 μL)', UUID(), 'CONSUMABLE', 'B栋304室', 500, 500, 'AVAILABLE'),
('一次性吸头 (200 μL)', UUID(), 'CONSUMABLE', 'B栋304室', 500, 490, 'AVAILABLE'),
('一次性吸头 (1000 μL)', UUID(), 'CONSUMABLE', 'B栋304室', 400, 400, 'AVAILABLE'),
('微量比色皿', UUID(), 'CONSUMABLE', 'B栋305室', 60, 60, 'AVAILABLE'),
('石英比色皿', UUID(), 'CONSUMABLE', 'B栋305室', 30, 30, 'AVAILABLE'),
('滤纸 (盒)', UUID(), 'CONSUMABLE', 'B栋306室', 80, 80, 'AVAILABLE'),
('微孔滤膜 (0.22 μm)', UUID(), 'CONSUMABLE', 'B栋306室', 50, 50, 'AVAILABLE'),
('微孔滤膜 (0.45 μm)', UUID(), 'CONSUMABLE', 'B栋306室', 50, 50, 'AVAILABLE'),
('载玻片 (盒)', UUID(), 'CONSUMABLE', 'B栋307室', 100, 100, 'AVAILABLE'),
('盖玻片 (盒)', UUID(), 'CONSUMABLE', 'B栋307室', 100, 100, 'AVAILABLE'),
('封口膜', UUID(), 'CONSUMABLE', 'B栋307室', 40, 40, 'AVAILABLE'),
('消毒酒精 (500 mL)', UUID(), 'CONSUMABLE', 'B栋308室', 60, 60, 'AVAILABLE'),
('次氯酸钠溶液', UUID(), 'CONSUMABLE', 'B栋308室', 30, 30, 'AVAILABLE'),
('洗手液', UUID(), 'CONSUMABLE', 'B栋308室', 40, 40, 'AVAILABLE'),
('Label 打印纸 (卷)', UUID(), 'CONSUMABLE', 'B栋309室', 20, 20, 'AVAILABLE'),
('记号笔 (盒)', UUID(), 'CONSUMABLE', 'B栋309室', 30, 30, 'AVAILABLE'),
('实验室胶带 (卷)', UUID(), 'CONSUMABLE', 'B栋309室', 25, 25, 'AVAILABLE'),
('GraphPad Prism 授权', UUID(), 'SOFTWARE', '网络授权', 15, 15, 'AVAILABLE'),
('SPSS 统计授权', UUID(), 'SOFTWARE', '网络授权', 10, 10, 'AVAILABLE'),
('AutoCAD 授权', UUID(), 'SOFTWARE', '网络授权', 5, 5, 'AVAILABLE'),
('SolidWorks 授权', UUID(), 'SOFTWARE', '网络授权', 5, 5, 'AVAILABLE'),
('Python 科学计算环境', UUID(), 'SOFTWARE', '服务器部署', 50, 50, 'AVAILABLE'),
('R 统计分析环境', UUID(), 'SOFTWARE', '服务器部署', 50, 50, 'AVAILABLE'),
('Adobe 创意套件', UUID(), 'SOFTWARE', '网络授权', 8, 8, 'AVAILABLE'),
('EndNote 文献管理', UUID(), 'SOFTWARE', '网络授权', 20, 20, 'AVAILABLE'),
('LabVIEW 开发授权', UUID(), 'SOFTWARE', '网络授权', 3, 3, 'AVAILABLE'),
('ANSYS 仿真授权', UUID(), 'SOFTWARE', 'HPC 集群', 4, 4, 'AVAILABLE'),
('COMSOL 多物理场', UUID(), 'SOFTWARE', 'HPC 集群', 3, 3, 'AVAILABLE'),
('Origin 数据绘图', UUID(), 'SOFTWARE', '网络授权', 12, 12, 'AVAILABLE'),
('ChemDraw 化学绘图', UUID(), 'SOFTWARE', '网络授权', 10, 10, 'AVAILABLE'),
('Schrödinger 分子模拟', UUID(), 'SOFTWARE', 'GPU 工作站', 2, 2, 'AVAILABLE'),
('移动式紫外灯', UUID(), 'OTHER', 'B栋401室', 10, 10, 'AVAILABLE'),
('液氮罐 (30 L)', UUID(), 'OTHER', 'B栋401室', 4, 4, 'AVAILABLE'),
('液氮罐 (10 L)', UUID(), 'OTHER', 'B栋401室', 6, 6, 'AVAILABLE'),
('气体钢瓶推车', UUID(), 'OTHER', 'B栋402室', 8, 8, 'AVAILABLE'),
('急救箱', UUID(), 'OTHER', '各楼层公共区', 15, 15, 'AVAILABLE'),
('护目镜', UUID(), 'OTHER', 'B栋403室', 40, 38, 'AVAILABLE'),
('白大褂', UUID(), 'OTHER', 'B栋403室', 30, 30, 'AVAILABLE'),
('实验用冰箱 (-20 °C)', UUID(), 'OTHER', 'B栋404室', 8, 8, 'AVAILABLE'),
('超低温冰箱 (-80 °C)', UUID(), 'OTHER', 'B栋404室', 4, 3, 'AVAILABLE'),
('制冰机', UUID(), 'OTHER', 'B栋405室', 3, 3, 'AVAILABLE'),
('碎纸机', UUID(), 'OTHER', 'C栋301室', 5, 5, 'AVAILABLE'),
('投影仪', UUID(), 'OTHER', 'C栋301室', 6, 6, 'AVAILABLE'),
('会议摄像头', UUID(), 'OTHER', 'C栋302室', 10, 10, 'AVAILABLE'),
('全自动细胞计数仪', UUID(), 'INSTRUMENT', 'A栋302室', 2, 2, 'AVAILABLE');
